ALTER ROLE postgres WITH PASSWORD '-_nmzTgeaWZx7GD2NIUYKKEK_PTNdy2a1KTY9lMmcfQ';
ALTER ROLE supabase_admin WITH PASSWORD '-_nmzTgeaWZx7GD2NIUYKKEK_PTNdy2a1KTY9lMmcfQ';
ALTER ROLE supabase_auth_admin WITH PASSWORD '-_nmzTgeaWZx7GD2NIUYKKEK_PTNdy2a1KTY9lMmcfQ';
ALTER ROLE supabase_storage_admin WITH PASSWORD '-_nmzTgeaWZx7GD2NIUYKKEK_PTNdy2a1KTY9lMmcfQ';
ALTER ROLE authenticator WITH PASSWORD '-_nmzTgeaWZx7GD2NIUYKKEK_PTNdy2a1KTY9lMmcfQ';
ALTER ROLE dashboard_user WITH PASSWORD '-_nmzTgeaWZx7GD2NIUYKKEK_PTNdy2a1KTY9lMmcfQ';
